### ISSUE TITLE
raise HIDException('unable to open device')

### ISSUE THREAD

**Issue by xevilstar** [ederfmartins/rgb_keyboard#5]
I have installed 

apt install libhidapi-libusb0 libhidapi-hidraw0 libhidapi-dev python3-hidapi

 /dev/input/event0    AT Translated Set 2 keyboard

 lsusb -d 048d:
Bus 003 Device 006: ID 048d:6008 Integrated Technology Express, Inc. ITE Device(8291)

keyboard_light -c red -p solid -s 1 -i 32
Traceback (most recent call last):
  File "/usr/local/bin/keyboard_light", line 33, in <module>
    sys.exit(load_entry_point('rgb-keyboard==1.0.0', 'console_scripts', 'keyboard_light')())
  File "/usr/local/lib/python3.9/dist-packages/rgb_keyboard-1.0.0-py3.9.egg/rgb_keyboard/__main__.py", line 48, in main
  File "/usr/local/lib/python3.9/dist-packages/rgb_keyboard-1.0.0-py3.9.egg/rgb_keyboard/driver.py", line 33, in send_args
  File "/usr/local/lib/python3.9/dist-packages/rgb_keyboard-1.0.0-py3.9.egg/rgb_keyboard/driver.py", line 36, in _send_command
  File "/usr/local/lib/python3.9/dist-packages/hid-1.0.4-py3.9.egg/hid/__init__.py", line 130, in __init__
    raise HIDException('unable to open device')
hid.HIDException: unable to open device

**Comment by ederfmartins** [comment]
Hello @xevilstar, 
your lsub command is pointing to a different product id so I suspect that your keyboard is not compatible with this drive.
 
Could you confirm that you have the right key board installed by running?
```
sudo hwinfo --keyboard
```
This should output something like:
```
...
Hardware Class: keyboard
Model: "Integrated Technology Express ITE Device(8291)"
Hotplug: USB
Vendor: usb 0x048d "Integrated Technology Express, Inc."
Device: usb 0xce00 "ITE Device(8291)"  
Revision: "0.02" 
...
```
I can patch the driver to your product id, but I wont be able to test it because I only have 048d:**ce00** Integrated Technology Express, Inc. ITE Device(8291) installed in my machine.

**Comment by xevilstar** [comment]
hwinfo --keyboard
32: USB 00.0: 10800 Keyboard                                    
  [Created at usb.122]
  Unique ID: 3+lx.CU+9bngwL46
  Parent ID: mZxt.JAwptI+a4y5
  SysFS ID: /devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb3/3-2/3-2.3/3-2.3:1.0
  SysFS BusID: 3-2.3:1.0
  Hardware Class: keyboard
  Model: "CASUE USB KB"
  Hotplug: USB
  Vendor: usb 0x2a7a 
  Device: usb 0x8a47 "CASUE USB KB"
  Revision: "0.01"
  Driver: "usbhid"
  Driver Modules: "usbhid"
  Device File: /dev/input/event8
  Device Files: /dev/input/event8, /dev/input/by-path/pci-0000:06:00.4-usb-0:2.3:1.0-event-kbd, /dev/input/by-id/usb-2a7a_CASUE_USB_KB-event-kbd
  Device Number: char 13:72
  Speed: 1.5 Mbps
  Module Alias: "usb:v2A7Ap8A47d0001dc00dsc00dp00ic03isc01ip01in00"
  Driver Info #0:
    XkbRules: xfree86
    XkbModel: pc104
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #42 (Hub)

37: USB 00.0: 10800 Keyboard
  [Created at usb.122]
  Unique ID: 86pP.mWvH0lYzry2
  Parent ID: CiZ2.d7FDLX76qXB
  SysFS ID: /devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb3/3-3/3-3.3/3-3.3:1.0
  SysFS BusID: 3-3.3:1.0
  Hardware Class: keyboard
  Model: "Integrated Technology Express ITE Device(8291)"
  Hotplug: USB
  Vendor: usb 0x048d "Integrated Technology Express, Inc."
  Device: usb 0x6008 "ITE Device(8291)"
  Revision: "0.03"
  Speed: 12 Mbps
  Module Alias: "usb:v048Dp6008d0003dc00dsc00dp00ic03isc01ip01in00"
  Driver Info #0:
    XkbRules: xfree86
    XkbModel: pc104
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #23 (Hub)

45: USB 00.0: 10800 Keyboard
  [Created at usb.122]
  Unique ID: Gves.ECUhYF2NlWE
  Parent ID: cLrx.lRoCB54l1cE
  SysFS ID: /devices/pci0000:00/0000:00:08.1/0000:06:00.3/usb1/1-2/1-2.2/1-2.2:1.0
  SysFS BusID: 1-2.2:1.0
  Hardware Class: keyboard
  Model: "Logitech USB Receiver"
  Hotplug: USB
  Vendor: usb 0x046d "Logitech, Inc."
  Device: usb 0xc539 "USB Receiver"
  Revision: "39.06"
  Driver: "usbhid"
  Driver Modules: "usbhid"
  Speed: 12 Mbps
  Module Alias: "usb:v046DpC539d3906dc00dsc00dp00ic03isc01ip01in00"
  Driver Info #0:
    XkbRules: xfree86
    XkbModel: pc104
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #28 (Hub)

47: PS/2 00.0: 10800 Keyboard
  [Created at input.226]
  Unique ID: nLyy.+49ps10DtUF
  Hardware Class: keyboard
  Model: "AT Translated Set 2 keyboard"
  Vendor: 0x0001 
  Device: 0x0001 "AT Translated Set 2 keyboard"
  Compatible to: int 0x0211 0x0001
  Device File: /dev/input/event0
  Device Files: /dev/input/event0, /dev/input/by-path/platform-i8042-serio-0-event-kbd
  Device Number: char 13:64
  Driver Info #0:
    XkbRules: xfree86
    XkbModel: pc104
  Config Status: cfg=new, avail=yes, need=no, active=unknown

**Comment by xevilstar** [comment]
bump ?

**Comment by xevilstar** [comment]
could I search and send you a keyboard ?

**Comment by xevilstar** [comment]
still doesn't work same error

lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 004: ID 8087:0029 Intel Corp. AX200 Bluetooth
Bus 003 Device 005: ID 048d:6008 Integrated Technology Express, Inc. ITE Device(8291)
Bus 003 Device 003: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 003 Device 002: ID 2a7a:8a47  CASUE USB KB
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 003: ID 05e3:0620 Genesys Logic, Inc. GL3523 Hub
Bus 002 Device 002: ID 0bda:0316 Realtek Semiconductor Corp. Card Reader
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 04f2:b71a Chicony Electronics Co., Ltd HD Webcam
Bus 001 Device 004: ID 046d:c539 Logitech, Inc. Cordless Mouse Receiver
Bus 001 Device 002: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

cat 50-usb-rgbkeyboard.conf 
SUBSYSTEM=="usb", ATTRS{idVendor}=="0x048d", ATTR{idProduct}=="0xce00", MODE="0666"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0x048d", ATTR{idProduct}=="0x6008", MODE="0666"
